package app.droprun;

import android.content.ComponentName;
import android.content.Context;
import android.content.Intent;
import android.graphics.Bitmap;
import android.graphics.Rect;
import android.graphics.drawable.GradientDrawable;
import android.graphics.drawable.RippleDrawable;
import android.os.Build;
import android.os.Bundle;
import android.os.SystemClock;
import android.view.View;
import android.view.ViewGroup;
import android.view.WindowInsets;
import android.widget.*;
import androidx.lifecycle.Lifecycle;
import androidx.test.core.app.ActivityScenario;
import androidx.test.platform.app.InstrumentationRegistry;
import org.json.*;
import org.junit.Test;
import java.io.File;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.StandardOpenOption;
import java.util.UUID;
import static app.droprun.ShareEditorTest.assertCompleteText;
import static app.droprun.ShareEditorTest.findText;
import static app.droprun.ShareSettingsHierarchyTest.bounds;
import static org.junit.Assert.*;

/** Six opt-in memory windows. No permission/mode/disconnect/preference click or business write. */
public class SettingsReadingPresentationTest {
    static boolean unresolvedLifetime;
    static final String[] IDS={"memory-mobile","memory-desktop"};
    @Test public void readingSectionsKeepChoicesAndProjectIdentity()throws Throwable{
        Bundle args=InstrumentationRegistry.getArguments();String phase=args.getString("settingsReadingProbe","");if(phase.isEmpty())return;assertTrue(phase.equals("baseline")||phase.equals("accepted"));
        boolean accepted=phase.equals("accepted");String capture=args.getString("captureSettingsReading","");assertTrue(capture.isEmpty()||capture.equals(phase));String nonce=args.getString("settingsReadingNonce","");if(capture.isEmpty())assertTrue(nonce.isEmpty());else assertEquals(UUID.fromString(nonce).toString(),nonce);
        assertTrue(Build.VERSION.SDK_INT>=30);assertFalse(unresolvedLifetime);Context target=InstrumentationRegistry.getInstrumentation().getTargetContext();assertTrue(target.getPackageName().endsWith(".debug"));assertFalse(TaskSyncService.running);assertFalse(target.getPackageManager().getActivityInfo(new ComponentName(target,DemoSettingsRecreationActivity.class),0).exported);
        File directory=null;if(!capture.isEmpty()){File base=target.getExternalFilesDir(null);assertNotNull(base);directory=new File(base,"ui-probe-evidence/settings-reading-"+nonce);assertFalse(directory.exists());assertTrue(directory.mkdirs());}
        float prior=DemoSettingsRecreationActivity.hierarchyFontScale;String priorLanguage=L.chinese()?"zh":"en";boolean destroyed=true;int entered=0,completed=0,closed=0,captured=0;
        try{for(String[] config:new String[][]{{"en","light","1"},{"en","dark","1"},{"zh","light","1"},{"zh","dark","1"},{"en","light","2"},{"zh","dark","2"}}){
            String identity=phase+"|"+String.join("|",config);float scale=Float.parseFloat(config[2]);assertTrue(destroyed);assertFalse(unresolvedLifetime);DemoSettingsRecreationActivity.hierarchyFontScale=scale;
            ActivityScenario<DemoSettingsRecreationActivity> scenario=null;Throwable failure=null;DemoSettingsRecreationActivity[] retained={null};boolean[] priorTouch={false};boolean touchChanged=false;
            try{
                destroyed=false;unresolvedLifetime=true;event(identity,"launch-attempt");scenario=ActivityScenario.launch(new Intent(target,DemoSettingsRecreationActivity.class).putExtra("language",config[0]).putExtra("appearance",config[1]).putExtra("modelHierarchy",true));event(identity,"returned-handle");ready(scenario);
                scenario.onActivity(a->{safe(a);retained[0]=a;priorTouch[0]=a.body.isInTouchMode();assertEquals(scale,a.getResources().getConfiguration().fontScale,0f);assertEquals(config[1].equals("dark"),Ui.dark);assertEquals(320,a.getResources().getConfiguration().screenWidthDp);seed(a);});ready(scenario);entered++;event(identity,"entered");
                for(int id:new int[]{R.id.settings_appearance,R.id.settings_language,R.id.settings_model,R.id.settings_effort}){
                    scenario.onActivity(a->{View row=a.body.findViewById(id);assertNotNull(row);row.requestRectangleOnScreen(new Rect(0,0,row.getWidth(),row.getHeight()),true);});frame(scenario);ready(scenario);
                    scenario.onActivity(a->{View row=a.body.findViewById(id);assertTrue(row.getHeight()>=Ui.dp(a,48));assertTrue(row.isClickable());assertTrue(row.isFocusable());assertTrue(row.getForeground() instanceof RippleDrawable);assertTrue(String.valueOf(row.getContentDescription()).contains(", "));assertPreferenceVisible(a,row);if(accepted){boolean modelGroup=id==R.id.settings_model||id==R.id.settings_effort;View parent=(View)row.getParent();assertEquals(Ui.dp(a,modelGroup?248:280),row.getWidth());if(modelGroup){assertTrue(parent.getBackground() instanceof GradientDrawable);GradientDrawable surface=(GradientDrawable)parent.getBackground();assertNotNull(surface.getColor());assertEquals(Ui.SURFACE,surface.getColor().getDefaultColor());}else assertNull(parent.getBackground());assertEquals(0f,parent.getElevation(),0f);}safe(a);});
                }
                scenario.onActivity(a->{a.showAccess=true;a.render();});ready(scenario);
                for(String id:IDS){
                    scenario.onActivity(a->{TextView name=projectName(a,id),chip=projectChip(a,id);assertEquals(a.store.projectLabel(id,sampleName()),name.getText().toString());assertCompleteText(name);assertTrue(name.getText().toString().contains(id.substring(0,8)));assertTrue(String.valueOf(chip.getContentDescription()).startsWith(name.getText().toString()));assertTrue(chip.getHeight()>=Ui.dp(a,48));assertTrue(chip.getWidth()>=Ui.dp(a,48));assertTrue(chip.isClickable());assertTrue(chip.isFocusable());assertTrue(chip.getForeground() instanceof RippleDrawable);if(accepted){ViewGroup row=(ViewGroup)name.getParent(),content=(ViewGroup)row.getParent(),disclosure=(ViewGroup)content.getParent();View surface=(View)disclosure.getParent();assertTrue(surface.getBackground() instanceof GradientDrawable);GradientDrawable fill=(GradientDrawable)surface.getBackground();assertNotNull(fill.getColor());assertEquals(Ui.SURFACE,fill.getColor().getDefaultColor());assertEquals(Ui.dpf(a,Ui.RADIUS_CARD),fill.getCornerRadius(),0f);assertEquals(Ui.dp(a,16),surface.getPaddingLeft());assertEquals(Ui.dp(a,16),surface.getPaddingRight());assertEquals(Ui.dp(a,12),surface.getPaddingTop());assertEquals(Ui.dp(a,12),surface.getPaddingBottom());assertEquals(0f,surface.getElevation(),0f);assertFalse(surface.isClickable());assertFalse(surface.isFocusable());assertNull(name.getEllipsize());assertTrue(name.getMaxLines()<0||name.getMaxLines()==Integer.MAX_VALUE);}if(accepted&&scale>=1.5f){assertEquals(Ui.dp(a,248),name.getWidth());assertSame(name.getParent(),chip.getParent());assertEquals(LinearLayout.VERTICAL,((LinearLayout)name.getParent()).getOrientation());Rect nameBounds=bounds(name),chipBounds=bounds(chip);assertEquals(nameBounds.left,chipBounds.left);assertTrue("Permission action follows the complete project name",chipBounds.top>=nameBounds.bottom+Ui.dp(a,8));}});
                    for(boolean tail:new boolean[]{false,true}){scenario.onActivity(a->{TextView name=projectName(a,id);name.requestRectangleOnScreen(line(name,tail),true);});ready(scenario);scenario.onActivity(a->{TextView name=projectName(a,id);Rect shown=new Rect();assertTrue(name.getLocalVisibleRect(shown));assertTrue("Requested project line including ID fits its visible text area",shown.contains(line(name,tail)));safe(a);});}
                    scenario.onActivity(a->{TextView chip=projectChip(a,id);chip.requestRectangleOnScreen(new Rect(0,0,chip.getWidth(),chip.getHeight()),true);});ready(scenario);scenario.onActivity(a->SettingsRecreationTest.assertCompleteAndVisible(a,projectChip(a,id)));
                }
                if(accepted){
                    boolean[] retentionHadKey={false},retentionChanged={false};Object[] retentionValue={null};Throwable retentionFailure=null;
                    scenario.onActivity(a->{safe(a);retentionHadKey[0]=a.cached.containsKey("retention");retentionValue[0]=a.cached.get("retention");});
                    try{for(boolean retentionValid:new boolean[]{false,true}){
                        if(retentionValid){scenario.onActivity(a->{safe(a);retentionChanged[0]=true;a.cached.put("retention","{\"rawDays\":14,\"artifactDays\":60}");a.render();});ready(scenario);}
                        String unknown=L.t("Connect, then use Refresh in Default model & effort to load your Relay’s retention policy.","联网后，在“默认模型强度”中点按刷新，获取中转服务保留策略。");
                        String[] retentionTexts=retentionValid?new String[]{L.t("Last synced Relay policy","上次同步的中转策略"),L.t("Original uploads · 14 days after a task ends","原始上传 · 14 天（任务结束后）"),L.t("Screenshots & files · 60 days after a task ends","截图与文件 · 60 天（任务结束后）")}:new String[]{unknown};
                        scenario.onActivity(a->{safe(a);if(retentionValid)assertNull(findText(a.body,unknown));else {assertNotNull(findText(a.body,unknown));assertNull(findText(a.body,L.t("Last synced Relay policy","上次同步的中转策略")));}});
                        String[] retentionNotes={L.t("Reports stay until you delete them. Preview links and snapshots have separate expiry times. Cleanup runs periodically and does not delete your computer’s project files or backups.","报告保留至你删除。预览链接与快照另有有效期。清理定期运行，不会删除电脑上的项目文件或备份。"),L.t("Change retention in your Relay deployment settings. This cached policy may be outdated while offline. Saved handoffs on this phone stay until sent or removed from project history.","在中转部署配置中修改保留期限。离线时，缓存的策略可能已过时。手机上的待发送副本保留至发送成功，或在项目历史中手动移除。")};
                        for(String[] retentionPart:new String[][]{retentionTexts,retentionNotes})for(String reading:retentionPart)for(boolean tail:new boolean[]{false,true}){
                            scenario.onActivity(a->{safe(a);TextView note=findText(a.body,reading);assertNotNull(note);assertCompleteText(note);note.requestRectangleOnScreen(line(note,tail),true);});ready(scenario);
                            scenario.onActivity(a->{TextView note=findText(a.body,reading);assertNotNull(note);assertCompleteText(note);Rect shown=new Rect();assertTrue(note.getLocalVisibleRect(shown));assertTrue("Requested retention paragraph line fits its visible text area",shown.contains(line(note,tail)));safe(a);});
                        }
                    }}catch(Throwable error){retentionFailure=error;throw error;}
                    finally{if(retentionChanged[0])try{
                        scenario.onActivity(a->{assertSame(retained[0],a);if(retentionHadKey[0])a.cached.put("retention",retentionValue[0]);else a.cached.remove("retention");a.render();assertEquals(retentionHadKey[0],a.cached.containsKey("retention"));assertSame(retentionValue[0],a.cached.get("retention"));safe(a);});ready(scenario);
                    }catch(Throwable restoreError){if(retentionFailure!=null)retentionFailure.addSuppressed(restoreError);else throw restoreError;}}
                }
                int[] scroll={0},focus={View.NO_ID};String[] values={null};scenario.onActivity(a->{scroll[0]=((ScrollView)a.findViewById(R.id.settings_scroll)).getScrollY();View current=a.getCurrentFocus();if(current!=null&&!current.isInTouchMode())focus[0]=current.getId();values[0]=a.store.defaultModel()+"|"+a.store.defaultEffort(a.store.defaultModel());a.render();});ready(scenario);
                scenario.onActivity(a->{assertTrue(a.showAccess);assertEquals(scroll[0],((ScrollView)a.findViewById(R.id.settings_scroll)).getScrollY());assertEquals(values[0],a.store.defaultModel()+"|"+a.store.defaultEffort(a.store.defaultModel()));if(focus[0]==R.id.settings_appearance||focus[0]==R.id.settings_language||focus[0]==R.id.settings_model||focus[0]==R.id.settings_effort)assertEquals(focus[0],a.getCurrentFocus().getId());safe(a);});
                if(accepted){InstrumentationRegistry.getInstrumentation().setInTouchMode(false);touchChanged=true;accessFocus(scenario);}
                if(scale==1f&&directory!=null){capture(scenario,directory,nonce,phase,config[0],config[1]);captured++;}
                if(accepted){scenario.onActivity(a->{a.busy=true;a.render();});ready(scenario);scenario.onActivity(a->{for(String id:IDS){TextView chip=projectChip(a,id);assertFalse(chip.isEnabled());assertEquals(.5f,chip.getAlpha(),0f);}safe(a);guards(identity,"memory-busy-disabled",a);a.busy=false;a.render();});ready(scenario);scenario.onActivity(a->{for(String id:IDS){TextView chip=projectChip(a,id);assertTrue(chip.isEnabled());assertEquals(1f,chip.getAlpha(),0f);}safe(a);guards(identity,"memory-idle-restored",a);});}
                scenario.onActivity(a->guards(identity,"before-close",a));completed++;event(identity,"full-completed");
            }catch(Throwable error){failure=error;throw error;}
            finally{if(scenario!=null)try{scenario.close();assertEquals(Lifecycle.State.DESTROYED,scenario.getState());destroyed=true;unresolvedLifetime=false;closed++;event(identity,"DESTROYED");if(retained[0]!=null){guards(identity,"after-destroyed",retained[0]);safe(retained[0]);}if(touchChanged){InstrumentationRegistry.getInstrumentation().setInTouchMode(priorTouch[0]);event(identity,"touch-mode-restored");}}catch(Throwable closeError){if(failure!=null)failure.addSuppressed(closeError);else throw closeError;}}
        }}finally{if(destroyed){DemoSettingsRecreationActivity.hierarchyFontScale=prior;L.language(priorLanguage);event(phase,"font-and-language-restored");}}
        assertEquals(6,entered);assertEquals(6,completed);assertEquals(6,closed);assertEquals(directory==null?0:4,captured);assertFalse(unresolvedLifetime);event(phase,"SUMMARY entered="+entered+" completed="+completed+" DESTROYED="+closed+" captures="+captured+" business_actions=not_invoked_by_test");
    }
    static void accessFocus(ActivityScenario<DemoSettingsRecreationActivity> scenario)throws Throwable{
        View[] old={null};String[] original={null};Throwable failure=null;
        scenario.onActivity(a->{safe(a);assertFalse(a.body.isInTouchMode());original[0]=(String)a.cached.get("projects");View header=a.body.findViewById(R.id.settings_access);assertNotNull(header);assertEquals(Boolean.TRUE,header.getTag());assertTrue(header.requestFocus());assertSame(header,a.getCurrentFocus());old[0]=header;a.render();});ready(scenario);
        scenario.onActivity(a->{View header=a.body.findViewById(R.id.settings_access);assertNotSame(old[0],header);assertSame(header,a.getCurrentFocus());assertEquals(Boolean.TRUE,header.getTag());assertPreferenceVisible(a,header);safe(a);});
        try{
            for(String id:IDS){
                scenario.onActivity(a->{TextView chip=projectChip(a,id);assertEquals("project-access:"+id,chip.getTag());assertTrue(chip.requestFocus());assertSame(chip,a.getCurrentFocus());old[0]=chip;a.render();});ready(scenario);
                scenario.onActivity(a->{TextView chip=projectChip(a,id);assertNotSame(old[0],chip);assertSame(chip,a.getCurrentFocus());assertEquals("project-access:"+id,chip.getTag());SettingsRecreationTest.assertCompleteAndVisible(a,chip);safe(a);});
            }
            scenario.onActivity(a->{try{JSONObject data=new JSONObject(original[0]);JSONArray projects=data.getJSONArray("projects");data.put("projects",new JSONArray().put(projects.getJSONObject(1)).put(projects.getJSONObject(0)));a.cached.put("projects",data.toString());old[0]=a.getCurrentFocus();a.render();}catch(JSONException error){throw new AssertionError(error);}});ready(scenario);
            scenario.onActivity(a->{assertNotSame(old[0],a.getCurrentFocus());assertSame(projectChip(a,IDS[1]),a.getCurrentFocus());assertTrue(projectChip(a,IDS[1]).isEnabled());SettingsRecreationTest.assertCompleteAndVisible(a,projectChip(a,IDS[1]));a.switching.add(IDS[1]);a.render();});ready(scenario);
            scenario.onActivity(a->{assertFalse(projectChip(a,IDS[1]).isEnabled());assertSame(a.body.findViewById(R.id.settings_access),a.getCurrentFocus());a.switching.remove(IDS[1]);a.render();});ready(scenario);
            scenario.onActivity(a->{assertTrue(projectChip(a,IDS[1]).isEnabled());assertSame(a.body.findViewById(R.id.settings_access),a.getCurrentFocus());assertTrue(projectChip(a,IDS[0]).requestFocus());a.showAccess=false;a.render();});ready(scenario);
            scenario.onActivity(a->{assertSame(a.body.findViewById(R.id.settings_access),a.getCurrentFocus());assertEquals(Boolean.FALSE,a.getCurrentFocus().getTag());a.showAccess=true;a.render();});ready(scenario);
            scenario.onActivity(a->{assertSame(a.body.findViewById(R.id.settings_access),a.getCurrentFocus());assertEquals(Boolean.TRUE,a.getCurrentFocus().getTag());safe(a);});
        }catch(Throwable error){failure=error;throw error;}
        finally{try{scenario.onActivity(a->{a.cached.put("projects",original[0]);a.switching.remove(IDS[1]);a.showAccess=true;a.render();assertSame(original[0],a.cached.get("projects"));safe(a);});ready(scenario);}catch(Throwable restoreError){if(failure!=null)failure.addSuppressed(restoreError);else throw restoreError;}}
    }
    static String sampleName(){return L.t("Studio research references — mobile experience","工作室参考资料归档 · 移动端交互体验");}
    static void seed(DemoSettingsRecreationActivity a){try{JSONObject data=a.store.projectsData();JSONArray projects=new JSONArray();for(int n=0;n<IDS.length;n++)projects.put(new JSONObject().put("id",IDS[n]).put("name",sampleName()).put("permission",new JSONObject().put("enabled",n==0)));data.put("projects",projects);a.cached.put("projects",data.toString());a.render();safe(a);}catch(JSONException error){throw new AssertionError(error);}}
    static TextView projectName(DemoSettingsRecreationActivity a,String id){TextView name=findText(a.body,a.store.projectLabel(id,sampleName()));assertNotNull(name);return name;}
    static TextView projectChip(DemoSettingsRecreationActivity a,String id){ViewGroup row=(ViewGroup)projectName(a,id).getParent();for(int n=0;n<row.getChildCount();n++){View child=row.getChildAt(n);if(child instanceof TextView&&child.isClickable())return (TextView)child;}fail("Permission chip is absent");return null;}
    static Rect line(TextView view,boolean tail){assertCompleteText(view);android.text.Layout layout=view.getLayout();int n=tail?layout.getLineForOffset(view.length()-1):0;return new Rect(view.getCompoundPaddingLeft()+(int)Math.floor(layout.getLineLeft(n)),view.getCompoundPaddingTop()+layout.getLineTop(n),view.getCompoundPaddingLeft()+(int)Math.ceil(layout.getLineRight(n)),view.getCompoundPaddingTop()+layout.getLineBottom(n));}
    static void assertPreferenceVisible(DemoSettingsRecreationActivity a,View view){
        if(view instanceof ImageView){
            assertEquals(View.VISIBLE,view.getVisibility());assertNotNull(((ImageView)view).getDrawable());android.graphics.Matrix matrix=new android.graphics.Matrix();view.transformMatrixToGlobal(matrix);android.graphics.RectF projected=new android.graphics.RectF(0,0,view.getWidth(),view.getHeight());matrix.mapRect(projected);Rect visible=new Rect();assertTrue(view.getGlobalVisibleRect(visible));assertEquals("The transformed glyph is fully visible, not clipped",new android.graphics.RectF(visible),projected);
            View scroll=a.findViewById(R.id.settings_scroll);Rect viewport=bounds(scroll);viewport.left+=scroll.getPaddingLeft();viewport.top+=scroll.getPaddingTop();viewport.right-=scroll.getPaddingRight();viewport.bottom-=scroll.getPaddingBottom();Rect safe=new Rect();a.getWindow().getDecorView().getWindowVisibleDisplayFrame(safe);assertTrue(safe.intersect(viewport));assertTrue("The complete transformed glyph fits the safe scroll viewport",new android.graphics.RectF(safe).contains(projected));
        }else{assertTrue("Entire preference node fits actual scroll and screen",SettingsRecreationTest.fullyVisible(a,view));if(view instanceof TextView)assertCompleteText((TextView)view);}
        if(view instanceof ViewGroup)for(int n=0;n<((ViewGroup)view).getChildCount();n++)assertPreferenceVisible(a,((ViewGroup)view).getChildAt(n));
    }
    static void safe(DemoSettingsRecreationActivity a){assertEquals(0,a.forbiddenActions.get());assertEquals(0,a.workFactories);assertEquals(0,a.modelSaves);assertFalse(a.store.paired());assertTrue(a.getIntent().getBooleanExtra("modelHierarchy",false));}
    static void event(String identity,String value){Bundle status=new Bundle();status.putString("stream","SETTINGS_READING_LIFETIME\t"+identity+"\t"+value+"\n");InstrumentationRegistry.getInstrumentation().sendStatus(0,status);}
    static void guards(String identity,String phase,DemoSettingsRecreationActivity a){event(identity,phase+" forbidden="+a.forbiddenActions.get()+" work_factories="+a.workFactories+" model_saves="+a.modelSaves);}
    static void ready(ActivityScenario<DemoSettingsRecreationActivity> scenario)throws Exception{long deadline=SystemClock.elapsedRealtime()+3000;boolean[] ready={false};do{InstrumentationRegistry.getInstrumentation().waitForIdleSync();scenario.onActivity(a->{View decor=a.getWindow().getDecorView();ready[0]=a.hasWindowFocus()&&decor.isAttachedToWindow()&&!decor.isLayoutRequested()&&!a.body.isLayoutRequested()&&a.body.getAlpha()==1f&&a.body.getTranslationY()==0f;});if(ready[0])return;Thread.sleep(20);}while(SystemClock.elapsedRealtime()<deadline);fail("Settings memory window did not settle");}
    static void frame(ActivityScenario<DemoSettingsRecreationActivity> scenario)throws Exception{java.util.concurrent.CountDownLatch next=new java.util.concurrent.CountDownLatch(1);scenario.onActivity(a->{View decor=a.getWindow().getDecorView();decor.getViewTreeObserver().addOnPreDrawListener(new android.view.ViewTreeObserver.OnPreDrawListener(){public boolean onPreDraw(){decor.getViewTreeObserver().removeOnPreDrawListener(this);next.countDown();return true;}});decor.invalidate();});assertTrue(next.await(3,java.util.concurrent.TimeUnit.SECONDS));}
    static Rect bodyRect(DemoSettingsRecreationActivity a,View view){Rect rect=new Rect(0,0,view.getWidth(),view.getHeight());a.body.offsetDescendantRectToMyCoords(view,rect);return rect;}
    static void capture(ActivityScenario<DemoSettingsRecreationActivity> scenario,File directory,String nonce,String phase,String language,String theme)throws Exception{
        boolean[] includeModel={false};scenario.onActivity(a->{View accessRow=(View)projectName(a,IDS[0]).getParent();Rect span=bodyRect(a,a.hierarchyNotice);span.union(bodyRect(a,accessRow));ScrollView scroll=a.findViewById(R.id.settings_scroll);int viewport=scroll.getHeight()-scroll.getPaddingTop()-scroll.getPaddingBottom();assertTrue("Marker and first access row fit the actual viewport",span.height()<=viewport);Rect withModel=new Rect(span);withModel.union(bodyRect(a,(View)a.body.findViewById(R.id.settings_model).getParent()));includeModel[0]=withModel.height()<=viewport;if(includeModel[0])span=withModel;a.body.requestRectangleOnScreen(span,true);});frame(scenario);frame(scenario);ready(scenario);long settled=SystemClock.elapsedRealtime();Thread.sleep(2000);ready(scenario);JSONObject[] metadata={null};
        scenario.onActivity(a->{safe(a);assertEquals(1f,a.getWindow().getAttributes().alpha,0f);WindowInsets insets=a.getWindow().getDecorView().getRootWindowInsets();assertNotNull(insets);assertFalse(insets.isVisible(WindowInsets.Type.ime()));assertTrue(SystemClock.elapsedRealtime()-settled>=2000);if(includeModel[0]){assertPreferenceVisible(a,a.body.findViewById(R.id.settings_model));assertPreferenceVisible(a,a.body.findViewById(R.id.settings_effort));}SettingsRecreationTest.assertCompleteAndVisible(a,a.hierarchyNotice);SettingsRecreationTest.assertCompleteAndVisible(a,findText(a.body,2+L.t(" projects · manage access"," 个项目 · 管理授权")));SettingsRecreationTest.assertCompleteAndVisible(a,projectName(a,IDS[0]));SettingsRecreationTest.assertCompleteAndVisible(a,projectChip(a,IDS[0]));try{JSONArray projects=new JSONArray();for(String id:IDS){TextView name=projectName(a,id),chip=projectChip(a,id);projects.put(new JSONObject().put("id",id).put("visible_name",name.getText()).put("name_bounds",bounds(name).toShortString()).put("name_width",name.getWidth()).put("name_lines",name.getLineCount()).put("chip_bounds",bounds(chip).toShortString()).put("chip_description",chip.getContentDescription()).put("chip_enabled",chip.isEnabled()).put("chip_alpha",chip.getAlpha()));}metadata[0]=new JSONObject().put("nonce",nonce).put("phase",phase).put("language",language).put("theme",theme).put("font_scale",1).put("memory_only",true).put("capture_accepted",false).put("fixture",a.getClass().getSimpleName()).put("scope","First project access row and memory marker; model rows only when model_rows_in_capture is true; not the full Settings page").put("model_rows_in_capture",includeModel[0]).put("marker",a.hierarchyNotice.getText()).put("model_row_bounds",bounds(a.body.findViewById(R.id.settings_model)).toShortString()).put("projects",projects).put("required_predraws_completed",2).put("settled_at_elapsed_ms",settled).put("capture_at_elapsed_ms",SystemClock.elapsedRealtime()).put("forbidden_actions",a.forbiddenActions.get()).put("work_factories",a.workFactories).put("model_saves",a.modelSaves).put("business_actions","not_invoked_by_test").put("system_bar_pixels_require_visual_review",true);}catch(JSONException error){throw new AssertionError(error);}});
        Bitmap image=InstrumentationRegistry.getInstrumentation().getUiAutomation().takeScreenshot();assertNotNull(image);String name="settings-reading-"+language+"-"+theme+"-font1";try{assertEquals(320,image.getWidth());assertEquals(640,image.getHeight());try(OutputStream out=Files.newOutputStream(new File(directory,name+".png").toPath(),StandardOpenOption.CREATE_NEW,StandardOpenOption.WRITE)){assertTrue(image.compress(Bitmap.CompressFormat.PNG,100,out));}try(OutputStream out=Files.newOutputStream(new File(directory,name+".json").toPath(),StandardOpenOption.CREATE_NEW,StandardOpenOption.WRITE)){out.write(metadata[0].toString(2).getBytes(StandardCharsets.UTF_8));}}finally{image.recycle();}
    }
}
