import { mkdir, writeFile, access, cp } from 'node:fs/promises';
import { resolve } from 'node:path';
const site = resolve(import.meta.dirname, '../landing');
const repo = 'https://github.com/MrMaii/droprun';
const origin = process.env.DROPRUN_SITE_URL || '';
const texts = {
en: {
 lang:'en', switch:'中文', switchUrl:'/zh/', nav:['How it works','Your control','Get started'], badge:'OPEN SOURCE · ANDROID + WINDOWS',
 title:'A little inspiration.<br>A real next step.', lead:'Share something worth building. Send it to an existing project. Let your local Codex take it from there.', start:'Get started', github:'Explore on GitHub', demo:'See it in motion', note:'Your computer. Your Cloudflare. Your project.', caption:'The actual DropRun Android app · demonstration data',
 intro:'LESS HANDOFF. MORE FOLLOW-THROUGH.', introTitle:'Good ideas deserve<br>more than a bookmark.', introBody:'The hard part isn’t finding inspiration. It’s getting it into the project, explaining the context, and finding out what actually happened. DropRun makes that a small, deliberate handoff.',
 stepsTitle:'From “look at this”<br>to “look what changed.”', steps:[['Share the spark.','A link, image, video or a few words. Use the Android share sheet and choose DropRun.'],['Give it a home.','Pick an existing project. Leave a note, or let the agent judge where the material is useful.'],['Come back to evidence.','See what was read, what changed, and how it was checked. Open screenshots, files and supported static previews.']],
 detailLabel:'BUILT AROUND YOUR PROJECTS', detailTitle:'Everything in its place.<br>Nothing in your way.', details:[['A quieter home.','Only projects you have handed work to. Tasks and dispatches stay together, with clear status and pending work.'],['A share, not a detour.','A compact sheet sits over the app you were using. Save your handoff and get back to your day.'],['A result you can inspect.','Screenshots and next actions come first. The complete report and evidence are there when you need them.']],
 controlLabel:'LOCAL EXECUTION. CLEAR BOUNDARIES.', controlTitle:'Yours, all the way through.', controls:[['Your infrastructure','Deploy one private Relay in your Cloudflare account. There is no DropRun account or shared hosted backend.'],['Your agent','Codex runs on your Windows computer, in the project you selected. Its login credentials stay there.'],['Your decisions','Choose direct execution or review the plan first. Publishing, payments and other high-risk actions still need approval.']],
 installLabel:'A FEW STEPS, ONCE.', installTitle:'Make room for<br>your next good idea.', installLead:'You’ll need Windows x64 with Codex, Android 8 or later, and your own Cloudflare account with the required services enabled.', install:[['01','Set up the computer','Download the Windows package. The local setup guide checks your tools and helps deploy your Relay.'],['02','Connect your phone','Install the Android APK. Scan the pairing code, check the server and computer, then choose project access.'],['03','Send something useful','Share a reference from another app. Follow its real progress and inspect the result.']],
 download:'Release downloads',guide:'Self-hosting guide',status:'Public preview · read the release notes before installing',cost:'The source is free. Cloudflare, transcription and Codex usage belong to your own accounts. Windows packages may show an unknown-publisher warning.',
 faqTitle:'Before you drop in.',faq:[['Does it run when my computer is off?','Your Relay can hold accepted handoffs while the computer is offline. Execution resumes when your Connector is online. This is not cloud-hosted coding.'],['Can it understand every video link?','No. Source access varies. DropRun reports the text, audio and frames it actually obtained. A link or cover image is never presented as a fully watched video.'],['What can I preview on my phone?','Reports, screenshots and files are the baseline. Supported static sites can have versioned snapshots. Live backend previews require your own domain and managed Cloudflare Tunnel.'],['Is there a paid DropRun subscription?','No official hosted service or subscription is included. You operate your own Relay and use your own Codex account. Provider limits and charges can still apply.'],['Is this already a stable release?','This is the public preview line. Release notes identify completed tests and remaining device, source-access and reliability validation. No success rate is claimed without evidence.']],
 final:'See something good?<br>Give it somewhere to go.',footer:'An open-source bridge from inspiration to execution.',privacy:'Data & privacy',docs:'Documentation'
},
zh: {
 lang:'zh-CN',switch:'English',switchUrl:'/',nav:['工作方式','由你掌控','开始使用'],badge:'开源 · ANDROID + WINDOWS',title:'一点灵感。<br>下一步，真的发生。',lead:'看到值得用的内容，转发给已有项目。让电脑上的 Codex 接着做。',start:'开始使用',github:'查看 GitHub',demo:'看看实际体验',note:'你的电脑。你的 Cloudflare。你的项目。',caption:'真实 DropRun Android 界面 · 演示数据',
 intro:'少一点交接，多一点进展',introTitle:'好想法，<br>不该只留在收藏夹。',introBody:'困难的不是找到灵感，而是把它带进项目、解释背景，再确认到底做成了什么。DropRun 把这段路变成一次清晰、轻量的交办。',stepsTitle:'从「看看这个」，<br>到「看看改了什么」。',steps:[['分享这一刻。','链接、图片、视频，或几句话。在 Android 系统分享菜单中选择 DropRun。'],['交给那个项目。','选择已有项目。有想法就留一句话，没有也可以让 agent 判断是否适用。'],['带着证据回来。','查看读到了什么、改了哪里、如何验证。打开截图、文件和支持的静态页面预览。']],
 detailLabel:'围绕你的项目',detailTitle:'各归其位。<br>自然顺手。',details:[['更安静的首页。','只显示交办过的项目。独立任务和交办次数归在一起，当前状态、待发送内容清楚可见。'],['分享，不必绕路。','轻量浮层覆盖在来源应用上。保存交办，继续刚才的事。'],['看得见的交付。','截图和下一步动作放在前面。需要细看时，完整报告与验证依据随时展开。']],
 controlLabel:'本地执行，边界清楚',controlTitle:'从头到尾，<br>由你掌控。',controls:[['自己的基础设施','Relay 部署在你的 Cloudflare 账号。没有 DropRun 注册账号，也没有共享的官方后台。'],['自己的 agent','Codex 在你的 Windows 电脑和选定项目中执行，登录凭证留在本机。'],['自己的决定','选择直接执行，或先看计划。发布、付费等高风险动作仍需单独批准。']],
 installLabel:'准备一次，接着使用',installTitle:'给下一个好想法，<br>留一个入口。',installLead:'需要已登录 Codex 的 Windows x64 电脑、Android 8 或更新手机，以及启用所需服务的个人 Cloudflare 账号。',install:[['01','准备电脑','下载 Windows 版本。本机向导检查工具，并帮助部署你自己的 Relay。'],['02','连接手机','安装 Android APK。扫码、核对电脑和服务器，再选择项目授权。'],['03','交办第一件事','从其他应用分享一份参考，跟踪真实进度，再检查交付结果。']],download:'下载发布版本',guide:'自部署指南',status:'公开预览版 · 安装前请阅读发布说明',cost:'源码免费。Cloudflare、转写与 Codex 用量归你自己的账号。Windows 安装包可能出现未知发布者提示。',
 faqTitle:'开始之前，讲清楚。',faq:[['电脑关机也能执行吗？','Relay 可以保存已接收的交办，等待电脑上线后执行。这不是云端托管的编码服务。'],['任意视频链接都能理解吗？','不能。内容来源和访问条件各不相同。DropRun 会说明实际取得的文本、音频和画面，不会把链接或封面说成完整看过的视频。'],['手机能预览什么？','基础交付包括报告、截图和文件。支持的静态网页可提供固定版本快照；需要后端的实时预览须配置自己的域名与 Cloudflare Tunnel。'],['需要购买 DropRun 订阅吗？','没有官方托管服务或订阅。你运行自己的 Relay，使用自己的 Codex 账号；供应商的额度与费用仍然适用。'],['已经是稳定正式版了吗？','当前是公开预览版。发布说明列出已完成的测试，以及真机、真实来源和可靠性验证的缺口；不虚构成功率。']],final:'看到好想法，<br>就让它有个去处。',footer:'把灵感交给项目的开源工具。',privacy:'数据与隐私',docs:'文档'
}};
const exists = async path => access(path).then(()=>true,()=>false);
const media = await exists(resolve(site,'media/home.png'));
if(process.argv.includes('--require-media')&&!media) throw new Error('Capture real Android screens before publishing.');
const cards = values => values.map(([t,p],i)=>`<article class="feature reveal"><span class="number">0${i+1}</span><h3>${t}</h3><p>${p}</p></article>`).join('');
for(const [locale,c] of Object.entries(texts)){
 const zh=locale==='zh';
 const html=`<!doctype html><html lang="${c.lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f7f8f2"><title>DropRun — ${zh?'你转发，它开工。':'Give inspiration a next step.'}</title><meta name="description" content="${c.lead}"><meta property="og:title" content="DropRun"><meta property="og:description" content="${c.lead}"><meta property="og:type" content="website">${origin?`<meta property="og:image" content="${origin}/media/social.png"><link rel="canonical" href="${origin}${zh?'/zh/':'/'}"><link rel="alternate" hreflang="en" href="${origin}/"><link rel="alternate" hreflang="zh-CN" href="${origin}/zh/">`:''}<link rel="icon" href="/brand-logo.png"><link rel="stylesheet" href="/styles.css"><script src="/app.js" defer></script></head><body>
<a class="skip" href="#main">${zh?'跳到正文':'Skip to content'}</a><header><a class="brand" href="${zh?'/zh/':'/'}"><img src="/brand-logo.png" width="34" height="34" alt=""><span>droprun<span class="dot">.</span></span></a><nav aria-label="${zh?'主导航':'Main navigation'}"><a href="#how">${c.nav[0]}</a><a href="#control">${c.nav[1]}</a><a href="${c.switchUrl}" lang="${zh?'en':'zh-CN'}">${c.switch}</a></nav><a class="button small" href="#install">${c.start}<span aria-hidden="true">↗</span></a></header>
<main id="main"><section class="hero wrap"><p class="eyebrow">${c.badge}</p><h1>${c.title}</h1><p class="lead">${c.lead}</p><div class="actions"><a class="button primary" href="#install">${c.start}<span aria-hidden="true">↗</span></a><a class="button secondary" href="${repo}">${c.github}</a></div><p class="smallprint">${c.note}</p>${media?`<div class="product-stage" id="demo"><figure class="phone main-phone"><img src="/media/${zh?'home-zh':'home'}.png" alt="${zh?'按项目归类的交办首页':'DropRun project home with grouped handoffs'}" width="432" height="936" fetchpriority="high"></figure><div class="stage-copy"><span class="eyebrow">${c.detailLabel}</span><h2>${c.details[0][0]}</h2><p>${c.details[0][1]}</p><a class="text-link" href="#experience">${c.demo} ↓</a></div></div><p class="caption">${c.caption}</p>`:''}</section>
<section class="intro wrap reveal"><p class="eyebrow">${c.intro}</p><div class="split"><h2>${c.introTitle}</h2><p>${c.introBody}</p></div></section>
<section class="how wrap" id="how"><p class="eyebrow">01 / ${c.nav[0]}</p><h2 class="reveal">${c.stepsTitle}</h2><div class="grid-three">${cards(c.steps)}</div></section>
<section class="experience" id="experience"><div class="wrap"><p class="eyebrow">02 / ${c.detailLabel}</p><h2 class="reveal">${c.detailTitle}</h2><div class="experience-grid">${media?`<figure class="phone detail-phone reveal"><img src="/media/settings.png" loading="lazy" alt="${zh?'连接与执行设置':'DropRun connection and execution settings'}" width="432" height="936"></figure>`:''}<div class="detail-list">${c.details.map(([t,p])=>`<article class="reveal"><h3>${t}</h3><p>${p}</p></article>`).join('')}</div></div>${await exists(resolve(site,'media/demo.mp4'))?`<video controls playsinline preload="none" poster="/media/home.png" aria-label="${c.demo}"><source src="/media/demo.mp4" type="video/mp4"><track default kind="captions" srclang="${zh?'zh':'en'}" src="/media/demo-${locale}.vtt" label="${zh?'中文':'English'}"></video>`:''}</div></section>
<section class="control wrap" id="control"><p class="eyebrow">03 / ${c.controlLabel}</p><h2 class="reveal">${c.controlTitle}</h2><div class="grid-three">${cards(c.controls)}</div></section>
<section class="install" id="install"><div class="wrap"><div class="split"><div><p class="eyebrow">${c.installLabel}</p><h2>${c.installTitle}</h2><p>${c.installLead}</p></div><ol class="install-list">${c.install.map(([n,t,p])=>`<li><span>${n}</span><div><h3>${t}</h3><p>${p}</p></div></li>`).join('')}</ol></div><div class="download-row"><div class="actions"><a class="button primary" href="${repo}/releases">${c.download}<span aria-hidden="true">↗</span></a><a class="button secondary" href="${repo}/blob/main/docs/technical/SELF_HOSTING${zh?'.zh-CN':''}.md">${c.guide}</a></div><p class="smallprint">${c.status}</p></div><p class="cost-note">${c.cost}</p></div></section>
<section class="faq wrap"><h2>${c.faqTitle}</h2><div>${c.faq.map(([q,a])=>`<details><summary>${q}<span aria-hidden="true">+</span></summary><p>${a}</p></details>`).join('')}</div></section>
<section class="closing wrap reveal"><img src="/brand-logo.png" width="64" height="64" alt=""><h2>${c.final}</h2><a class="button primary" href="#install">${c.start}<span aria-hidden="true">↗</span></a></section></main>
<footer class="wrap"><div><a class="brand" href="#main">droprun<span class="dot">.</span></a><p>${c.footer}</p></div><nav aria-label="${zh?'页脚':'Footer'}"><a href="${repo}">GitHub</a><a href="${repo}/tree/main/docs">${c.docs}</a><a href="${repo}/blob/main/docs/technical/PRIVACY.md">${c.privacy}</a><a href="${repo}/blob/main/LICENSE">Apache-2.0</a></nav><p class="copyright">© 2026 DropRun contributors</p></footer></body></html>`;
 const out=zh?resolve(site,'zh'):site;await mkdir(out,{recursive:true});await writeFile(resolve(out,'index.html'),html);
}
await writeFile(resolve(site,'robots.txt'),`User-agent: *\nAllow: /\n${origin?`Sitemap: ${origin}/sitemap.xml\n`:''}`);
if(origin)await writeFile(resolve(site,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>${origin}/</loc></url><url><loc>${origin}/zh/</loc></url></urlset>`);
const dist = resolve(site, 'dist');
await mkdir(dist, { recursive: true });
for (const name of ['index.html', 'zh', 'styles.css', 'app.js', 'brand-logo.png', 'robots.txt', 'sitemap.xml', 'media']) {
 if (await exists(resolve(site, name))) await cp(resolve(site, name), resolve(dist, name), { recursive: true });
}
console.log(JSON.stringify({pages:['/','/zh/'],realScreenshots:media,origin:origin||'not deployed',output:dist}));
