import { mkdir, writeFile, access, cp } from 'node:fs/promises';
import { resolve } from 'node:path';

const site = resolve(import.meta.dirname, '../landing');
const repo = 'https://github.com/MrMaii/droprun';
const release = 'v0.5.6-rc.1';
const downloads = `${repo}/releases/download/${release}`;
const origin = process.env.DROPRUN_SITE_URL || '';
const texts = {
en: {
 lang:'en', switch:'中文', switchUrl:'/zh/', nav:['The handoff','Your control'], badge:'OPEN SOURCE · SELF-HOSTED', light:'Light', dark:'Dark', appearanceLabel:'Dark appearance',
 title:'Good ideas.<br><span>Put in motion.</span>', lead:'Share from Android into an existing project. Your local Codex on Windows takes it forward. Inspect the result on your phone.', start:'Start installing', github:'View GitHub', watch:'Watch the UI tour', note:'Android + Windows · Your own Cloudflare Relay', caption:'Development UI preview · actual Android app · demo data, no agent task sent',
 heroHome:'Projects, together.', heroShare:'An idea, handed over.',
 demoLabel:'A CLOSER LOOK', demoTitle:'A small handoff.<br>A clear next step.', demoBody:'Stay in the app where you found it. Choose a project, add a little direction, and leave the rest with your computer.', demoNote:'9-second development UI tour. Demonstration data; this is not a real Codex execution.',
 stepsLabel:'FROM PHONE TO PROJECT', stepsTitle:'One idea.<br>Three simple moves.', stepsLead:'Keep the context close. Work lands in the project you already know, without another workspace to manage.', stepNav:'Explore the handoff', stepNames:['Share','Choose a project','Inspect the result'],
 steps:[['Share what caught your eye.','A link, image, video, or a few words. Choose DropRun from the Android share menu. A small sheet keeps you close to the source.','Add a note if you have a direction in mind.'],['Give it the right home.','Choose an existing Codex project. The phone brings recent handoffs together by project, with separate task and dispatch counts.','The full project directory stays available when you share.'],['Come back to something you can inspect.','Check what was read, what changed, and what needs your attention. Continue the same conversation when you have a follow-up.','A locally saved handoff is distinct from a server receipt or completed work.']],
 resultLabel:'DELIVERY, WITH CONTEXT', resultTitle:'More than<br>“done.”', resultLead:'A result should explain itself. DropRun brings the next action and the evidence to the front.', results:[['What it actually read','Text, audio, frames, or only metadata. Source limits stay visible.'],['What happened next','A readable report, screenshots, files, and supported static previews.'],['Where you take over','Review a plan, approve a scoped action, ask a follow-up, or stop the task.']],
 controlLabel:'LOCAL EXECUTION. CLEAR BOUNDARIES.', controlTitle:'Your projects.<br>Your say.', controlLead:'A bridge to your own setup. No DropRun account, shared backend, or hosted coding subscription.', controls:[['Your infrastructure','Deploy your private Relay in your own Cloudflare account. It carries materials and delivery between your phone and computer.'],['Your local Codex','Codex works in the selected project on your Windows computer. Your Codex login credentials stay on that computer.'],['Your decisions','Choose direct execution or plan review. Publishing, payments, and other high-risk actions still require separate approval.']],
 installLabel:'SET IT UP ONCE', installTitle:'Ready for your<br>next good idea.', installLead:'Windows x64 with signed-in Codex. Android 8 or newer. Your own Cloudflare account with the required services enabled.', install:[['01','Prepare your computer','The Windows setup checks your tools and helps deploy your own Relay.'],['02','Pair your phone','Install the APK, scan the code, verify the computer and server, and choose project access.'],['03','Make the first handoff','Share a reference, follow the received task, and inspect its actual delivery.']],
 windows:'For your computer', windowsDetail:'Windows x64 · per-user installation', installer:'Windows installer', portable:'Portable ZIP', android:'For your phone', androidDetail:'Android 8+ · direct APK installation', apk:'Android APK', guide:'Read the self-hosting guide', releaseNotes:'Release notes & checksums', status:'Public preview · 0.5.6-rc.1', cost:'DropRun source is free. Cloudflare, transcription, and Codex usage are billed or limited by your own providers. The Windows package is unsigned and may show an unknown-publisher prompt.', downloadNote:'Screens and tours show the 0.5.1 development UI captured October 5, 2026 with labelled demo data. They predate the later UX refinements and are not recordings of the 0.5.6-rc.1 download.',
 faqLabel:'GOOD TO KNOW', faqTitle:'A few things<br>up front.', faq:[['Does it work while my computer is off?','The Relay can hold accepted handoffs while your computer is offline. Execution waits for the Connector to come online. This is not a cloud-hosted coding service.'],['Can it understand every video link?','No. Access depends on the source. DropRun reports the text, audio, and frames it actually obtained. A link or cover image is never presented as a fully watched video.'],['What can I preview on my phone?','Reports, screenshots, and files are the baseline. Supported static sites can have versioned snapshots. Live backend previews need your own domain and managed Cloudflare Tunnel.'],['Do I need a DropRun subscription?','No official hosted service or subscription is included. You run your own Relay and use your own Codex account. Provider limits and usage charges still apply.'],['Is this a stable release?','This is a public preview. Release notes list completed checks and remaining real-device, source-access, and reliability acceptance. Interface demos do not establish that those gates have passed.']],
 final:'Keep the idea.<br>Move it forward.', footer:'From inspiration to an inspectable next step.', privacy:'Data & privacy', docs:'Documentation', source:'Apache-2.0 · Open source', homeAlt:'Recent handoffs grouped by project in the actual DropRun Android app', shareAlt:'The actual DropRun Android share sheet with project selection', taskAlt:'The actual DropRun task report with delivery and follow-up controls',
},
zh: {
 lang:'zh-CN', switch:'English', switchUrl:'/', nav:['一次交办','由你掌控'], badge:'开源 · 自部署', light:'浅色', dark:'深色', appearanceLabel:'深色外观',
 title:'你转发。<br><span>它接着做。</span>', lead:'从 Android 分享到已有项目。Windows 电脑上的本地 Codex 接着工作，手机查看可核验的交付。', start:'开始安装', github:'查看 GitHub', watch:'观看界面演示', note:'Android + Windows · 使用你自己的 Cloudflare Relay', caption:'开发预览 · 真实 Android 界面 · 演示数据，未发送 agent 任务',
 heroHome:'项目，各归其位。', heroShare:'灵感，交到手里。',
 demoLabel:'靠近一点，看清体验', demoTitle:'交办很轻。<br>下一步很清楚。', demoBody:'留在发现灵感的应用里。选一个项目，给一点方向，让电脑接着处理。', demoNote:'12 秒开发版界面演示。使用演示数据，不代表真实 Codex 执行。',
 stepsLabel:'从手机，走进项目', stepsTitle:'一个好想法。<br>三个简单动作。', stepsLead:'不用重新整理上下文，也不用再管理一个工作空间。材料交给你已经熟悉的项目。', stepNav:'查看交办流程', stepNames:['分享材料','选择项目','检查交付'],
 steps:[['把这一刻分享出去。','链接、图片、视频，或几句话。在 Android 分享菜单中选择 DropRun，小浮层让你始终靠近内容来源。','有明确想法，就补一句留言。'],['交给那个合适的项目。','选择已有 Codex 项目。最近交办按项目归类，独立任务和交办次数分别记录。','完整项目目录，在分享时随时可选。'],['带着看得懂的交付回来。','看看读到了什么、改了哪里、哪些事需要你处理。有追问时，继续同一段对话。','本机保存、服务端接收和完成执行，是不同状态。']],
 resultLabel:'交付，也交代清楚', resultTitle:'不只是一句<br>「完成了」。', resultLead:'一个结果，应该能解释自己。下一步动作与证据，放在你最先看到的地方。', results:[['实际读到了什么','文本、音频、画面，或仅元数据。来源限制清楚呈现。'],['接着做了什么','可读报告、截图、文件，以及支持的静态页面快照。'],['什么时候交还给你','审计划、批准具体动作、继续追问，或停止任务。']],
 controlLabel:'本地执行，边界清楚', controlTitle:'你的项目。<br>你来决定。', controlLead:'连接你自己的设备与服务。没有 DropRun 登录账号、共享后台或托管编码订阅。', controls:[['自己的基础设施','Relay 部署在你的 Cloudflare 账号，为手机和电脑中转材料与交付。'],['自己的本地 Codex','Codex 在 Windows 电脑上选定的项目里工作。Codex 登录凭证保存在本机。'],['自己的决定','选择直接执行，或先看计划。发布、付费等高风险动作，仍需单独批准。']],
 installLabel:'准备一次，接着使用', installTitle:'为下一个好想法，<br>准备一个入口。', installLead:'已登录 Codex 的 Windows x64 电脑。Android 8 或更新手机。启用所需服务的个人 Cloudflare 账号。', install:[['01','准备电脑','Windows 向导检查工具，帮助部署你自己的 Relay。'],['02','连接手机','安装 APK，扫码核对电脑和服务器，再选择项目授权。'],['03','交办第一件事','分享一份参考，跟踪收到的任务，检查实际交付。']],
 windows:'给你的电脑', windowsDetail:'Windows x64 · 按用户安装', installer:'Windows 安装包', portable:'便携 ZIP', android:'给你的手机', androidDetail:'Android 8+ · 直接安装 APK', apk:'Android APK', guide:'阅读自部署指南', releaseNotes:'发布说明与校验值', status:'公开预览版 · 0.5.6-rc.1', cost:'DropRun 源码免费。Cloudflare、转写和 Codex 的用量与费用，由你自己的供应商决定。Windows 安装包未签名，可能出现未知发布者提示。', downloadNote:'截图与录屏来自 2026 年 10 月 5 日的 0.5.1 开发界面，使用标注的演示数据。它们早于后续体验优化，并非 0.5.6-rc.1 下载包的录屏。',
 faqLabel:'开始之前，讲清楚', faqTitle:'几件事，<br>先说明白。', faq:[['电脑关机，也能执行吗？','Relay 可以保留已接收的交办，等待电脑上的 Connector 上线后执行。这不是云端托管的编码服务。'],['任意视频链接，都能理解吗？','不能，内容访问取决于来源。DropRun 会说明实际取得的文本、音频和画面，不会把链接或封面说成完整看过的视频。'],['手机能预览什么？','基础交付包括报告、截图和文件。支持的静态网页可提供固定版本快照；需要后端的实时预览，须配置你自己的域名与 Cloudflare Tunnel。'],['需要购买 DropRun 订阅吗？','没有官方托管服务或订阅。你运行自己的 Relay，使用自己的 Codex 账号；供应商的额度与用量费用仍然适用。'],['已经是稳定正式版了吗？','当前是公开预览版。发布说明列出已完成的检查，以及真机、真实来源和可靠性验收的缺口。界面演示不代表这些门槛已经通过。']],
 final:'留住好想法。<br>让它继续向前。', footer:'把灵感，交给可核验的下一步。', privacy:'数据与隐私', docs:'文档', source:'Apache-2.0 · 开源', homeAlt:'真实 DropRun Android 首页，交办按项目归类', shareAlt:'真实 DropRun Android 分享浮层与项目选择', taskAlt:'真实 DropRun 任务报告、交付与追问入口',
},
};

const exists = async path => access(path).then(() => true, () => false);
const screenshots = ['home', 'share', 'task'].flatMap(name => ['', '-zh'].flatMap(language => ['', '-dark'].map(theme => `media/${name}${language}${theme}.png`)));
const requiredAssets = ['styles.css', 'app.js', 'brand-logo.png', ...screenshots, 'media/ui-tour-en.mp4', 'media/ui-tour-zh.mp4', 'media/ui-tour-en.vtt', 'media/ui-tour-zh.vtt', ...(origin ? ['media/social.png'] : [])];
const missing = [];
for (const asset of requiredAssets) if (!await exists(resolve(site, asset))) missing.push(asset);
if (missing.length) throw new Error('Missing landing assets: ' + missing.join(', ') + '. Capture real app media before building; --require-media checks every used asset.');
const arrow = '<span aria-hidden="true">↗</span>';
const cards = values => values.map(([title, body], index) => `<article class="control-card reveal"><span class="card-number">0${index + 1}</span><h3>${title}</h3><p>${body}</p></article>`).join('');

for (const [locale, c] of Object.entries(texts)) {
 const zh = locale === 'zh';
 const home = zh ? 'home-zh.png' : 'home.png';
 const darkHome = zh ? 'home-zh-dark.png' : 'home-dark.png';
 const guide = `${repo}/blob/main/docs/technical/SELF_HOSTING${zh ? '.zh-CN' : ''}.md`;
 const screen = (name, alt, priority = false) => `<figure class="app-screen"><picture><source data-dark-screen srcset="/media/${name}${zh ? '-zh' : ''}-dark.png" media="(prefers-color-scheme:dark)"><img src="/media/${name}${zh ? '-zh' : ''}.png" alt="${alt}" width="320" height="640" ${priority ? 'fetchpriority="high"' : 'loading="lazy"'}></picture></figure>`;
 const steps = c.steps.map(([title, body, note], index) => `<article class="step-panel" id="panel-${index}" data-step-panel><div class="step-copy"><p class="eyebrow">0${index + 1} / ${c.stepNames[index]}</p><h3>${title}</h3><p>${body}</p><p class="step-note">${note}</p></div><div class="step-visual">${screen(['share', 'home', 'task'][index], [c.shareAlt, c.homeAlt, c.taskAlt][index])}<p class="caption">${c.caption}</p></div></article>`).join('');
 const html = `<!doctype html>
<html lang="${c.lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light dark"><meta name="theme-color" content="#F7F7F2" media="(prefers-color-scheme:light)"><meta name="theme-color" content="#171B18" media="(prefers-color-scheme:dark)"><title>DropRun — ${zh ? '你转发。它接着做。' : 'Good ideas. Put in motion.'}</title><meta name="description" content="${c.lead}"><meta property="og:title" content="DropRun — ${zh ? '你转发。它接着做。' : 'Good ideas. Put in motion.'}"><meta property="og:description" content="${c.lead}"><meta property="og:type" content="website">${origin ? `<meta property="og:url" content="${origin}${zh ? '/zh/' : '/'}"><meta property="og:image" content="${origin}/media/social.png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="${zh ? 'DropRun 公开预览与使用演示数据的真实 Android 界面' : 'DropRun public preview with an actual Android screen and labelled demonstration data'}"><meta name="twitter:card" content="summary_large_image"><link rel="canonical" href="${origin}${zh ? '/zh/' : '/'}"><link rel="alternate" hreflang="en" href="${origin}/"><link rel="alternate" hreflang="zh-CN" href="${origin}/zh/"><link rel="alternate" hreflang="x-default" href="${origin}/">` : ''}<link rel="icon" href="/brand-logo.png"><link rel="stylesheet" href="/styles.css"><script src="/app.js" defer></script></head>
<body><a class="skip" href="#main">${zh ? '跳到正文' : 'Skip to content'}</a>
<header class="site-header"><a class="brand" href="${zh ? '/zh/' : '/'}"><img src="/brand-logo.png" width="36" height="36" alt=""><span>droprun<span class="brand-dot">.</span></span></a><nav aria-label="${zh ? '主导航' : 'Main navigation'}"><a class="desktop-link" href="#how">${c.nav[0]}</a><a class="desktop-link" href="#control">${c.nav[1]}</a><a class="language-link" href="${c.switchUrl}" lang="${zh ? 'en' : 'zh-CN'}">${c.switch}</a><button class="appearance-toggle" type="button" data-appearance-toggle data-light="${c.light}" data-dark="${c.dark}" aria-label="${c.appearanceLabel}" aria-pressed="false" hidden>${c.light}</button></nav><a class="button compact primary" href="#install">${c.start}${arrow}</a></header>
<main id="main" tabindex="-1">
<section class="hero wrap"><div class="hero-copy"><p class="eyebrow">DropRun / ${c.badge}</p><h1>${c.title}</h1><p class="lead">${c.lead}</p><div class="actions"><a class="button primary" href="#install">${c.start}${arrow}</a><a class="button secondary" href="${repo}">${c.github}</a></div><a class="text-link watch-link" href="#demo">${c.watch}<span aria-hidden="true">→</span></a><p class="platform-note">${c.note}</p></div><div class="hero-media"><div class="hero-screens"><div class="hero-home">${screen('home', c.homeAlt, true)}<p class="screen-label">${c.heroHome}</p></div><div class="hero-share">${screen('share', c.shareAlt)}<p class="screen-label">${c.heroShare}</p></div></div><p class="caption">${c.caption}</p></div></section>
<section class="demo-section wrap" id="demo"><div class="demo-card reveal"><div class="demo-copy"><p class="eyebrow">${c.demoLabel}</p><h2>${c.demoTitle}</h2><p>${c.demoBody}</p><a class="text-link" href="#how">${c.nav[0]}<span aria-hidden="true">↓</span></a></div><figure class="demo-video"><video controls playsinline preload="none" poster="/media/${home}" data-light-poster="/media/${home}" data-dark-poster="/media/${darkHome}" aria-label="${c.watch}" aria-describedby="demo-caption"><source src="/media/ui-tour-${locale}.mp4" type="video/mp4"><track default kind="captions" srclang="${zh ? 'zh' : 'en'}" src="/media/ui-tour-${locale}.vtt" label="${zh ? '中文' : 'English'}"></video><figcaption id="demo-caption">${c.demoNote}</figcaption></figure></div></section>
<section class="flow-section wrap" id="how"><div class="section-heading reveal"><p class="eyebrow">${c.stepsLabel}</p><h2>${c.stepsTitle}</h2><p>${c.stepsLead}</p></div><div class="flow" data-stepper><div class="step-tabs" data-step-tabs aria-label="${c.stepNav}" hidden>${c.stepNames.map((name, index) => `<button type="button" id="step-${index}" data-step="${index}"><span class="step-number">0${index + 1}</span>${name}</button>`).join('')}</div><div class="step-panels">${steps}</div></div></section>
<section class="result-section"><div class="wrap result-grid"><div class="result-visual reveal">${screen('task', c.taskAlt)}<p class="caption">${c.caption}</p></div><div class="result-copy"><p class="eyebrow">${c.resultLabel}</p><h2 class="reveal">${c.resultTitle}</h2><p class="section-lead">${c.resultLead}</p><div class="result-details">${c.results.map(([title, body]) => `<article class="reveal"><h3>${title}</h3><p>${body}</p></article>`).join('')}</div></div></div></section>
<section class="install-section" id="install"><div class="wrap"><div class="install-heading"><div><p class="eyebrow">${c.installLabel}</p><h2>${c.installTitle}</h2><p class="section-lead">${c.installLead}</p><div class="actions install-entry"><a class="button primary" href="${downloads}/DropRun-0.5.6-windows-x64-setup.exe">${c.installer}${arrow}</a><a class="button secondary" href="${guide}">${c.guide}<span aria-hidden="true">→</span></a></div></div><ol class="install-steps">${c.install.map(([number, title, body]) => `<li><span>${number}</span><div><h3>${title}</h3><p>${body}</p></div></li>`).join('')}</ol></div><div class="download-grid"><article class="download-card"><p class="eyebrow">${c.windows}</p><h3>Windows</h3><p>${c.windowsDetail}</p><div class="actions"><a class="button primary" href="${downloads}/DropRun-0.5.6-windows-x64-setup.exe">${c.installer}${arrow}</a><a class="text-link" href="${downloads}/DropRun-0.5.6-windows-x64.zip">${c.portable}${arrow}</a></div></article><article class="download-card"><p class="eyebrow">${c.android}</p><h3>Android</h3><p>${c.androidDetail}</p><a class="button primary" href="${downloads}/DropRun-0.5.6-android.apk">${c.apk}${arrow}</a></article></div><div class="install-links"><a class="text-link" href="${guide}">${c.guide}<span aria-hidden="true">→</span></a><a class="text-link" href="${repo}/releases/tag/${release}">${c.releaseNotes}<span aria-hidden="true">→</span></a></div><div class="release-note"><strong>${c.status}</strong><div><p>${c.cost}</p><p class="download-difference">${c.downloadNote}</p></div></div></div></section>
<section class="control-section wrap" id="control"><div class="section-heading reveal"><p class="eyebrow">${c.controlLabel}</p><h2>${c.controlTitle}</h2><p>${c.controlLead}</p></div><div class="control-grid">${cards(c.controls)}</div></section>
<section class="faq-section wrap"><div><p class="eyebrow">${c.faqLabel}</p><h2>${c.faqTitle}</h2></div><div class="faq-list">${c.faq.map(([question, answer]) => `<details><summary>${question}<span class="disclosure-mark" aria-hidden="true">+</span></summary><div data-answer><p>${answer}</p></div></details>`).join('')}</div></section>
<section class="closing wrap reveal"><img src="/brand-logo.png" width="72" height="72" alt=""><h2>${c.final}</h2><a class="button primary" href="#install">${c.start}${arrow}</a></section>
</main><footer class="wrap"><div><a class="brand" href="#main"><img src="/brand-logo.png" width="32" height="32" alt=""><span>droprun<span class="brand-dot">.</span></span></a><p>${c.footer}</p></div><nav aria-label="${zh ? '页脚' : 'Footer'}"><a href="${repo}">GitHub</a><a href="${repo}/tree/main/docs">${c.docs}</a><a href="${repo}/blob/main/docs/technical/PRIVACY.md">${c.privacy}</a><a href="${repo}/blob/main/LICENSE">Apache-2.0</a></nav><p class="copyright">© 2026 DropRun contributors · ${c.source}</p></footer></body></html>`;
 const out = zh ? resolve(site, 'zh') : site;
 await mkdir(out, { recursive: true }); await writeFile(resolve(out, 'index.html'), html);
}
await writeFile(resolve(site, 'robots.txt'), `User-agent: *\nAllow: /\n${origin ? `Sitemap: ${origin}/sitemap.xml\n` : ''}`);
if (origin) await writeFile(resolve(site, 'sitemap.xml'), `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>${origin}/</loc></url><url><loc>${origin}/zh/</loc></url></urlset>`);
const dist = resolve(site, 'dist');
await mkdir(dist, { recursive: true });
for (const name of ['index.html', 'zh', 'styles.css', 'app.js', 'brand-logo.png', 'robots.txt', 'sitemap.xml', 'media']) if (await exists(resolve(site, name))) await cp(resolve(site, name), resolve(dist, name), { recursive: true });
console.log(JSON.stringify({ pages: ['/', '/zh/'], realScreenshots: true, checkedAssets: requiredAssets.length, origin: origin || 'not deployed', output: dist }));
