const token = location.hash.slice(1);
history.replaceState(null, '', location.pathname);
let language = navigator.language.startsWith('zh') ? 'zh' : 'en';
const el = id => document.getElementById(id);
function translate() { document.documentElement.lang = language === 'zh' ? 'zh-CN' : 'en'; document.querySelectorAll('[data-en]').forEach(node => { const value = node.dataset[language]; if (node.tagName === 'H1') node.innerHTML = value; else node.textContent = value; }); el('language').textContent = language === 'zh' ? 'English' : '中文'; }
el('language').onclick = () => { language = language === 'en' ? 'zh' : 'en'; translate(); };
async function api(path, body) { const response = await fetch('/api/' + path, { method: body === undefined ? 'GET' : 'POST', headers: { 'X-DropRun-Setup': token, 'Content-Type': 'application/json' }, body: body === undefined ? undefined : JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); return result; }
async function act(path, body = {}) { try { await api(path, body); await refresh(); } catch (error) { el('error').textContent = error.message; } }
async function doctor() { try { const data = await api('doctor'); el('doctor').replaceChildren(); for (const [name, value] of [['Node', true], ['Git', data.git], ['Codex', data.codex], ['Browser', data.browser], ['Wrangler', data.wrangler], ['Media tools', Object.values(data.media).every(Boolean)]]) { const badge = document.createElement('span'); badge.className = 'check' + (value ? '' : ' missing'); badge.textContent = `${value ? '✓' : '○'} ${name}`; el('doctor').append(badge); } const status = data.codexStatus; const hints = { 'missing': ['Install Codex desktop, then sign in.', '请安装 Codex 桌面版并登录。'], 'login-required': ['Sign in to Codex, then check again.', '请登录 Codex 后重新检查。'], 'unsupported': ['Update Codex desktop: this version does not support the required project API.', '请更新 Codex 桌面版：当前版本不支持所需项目接口。'], 'app-server-failed': ['Codex app server could not start. Open Codex and try again.', 'Codex 服务未启动。请先打开 Codex 后重试。'], 'timeout': ['Codex did not respond within 10 seconds. Open Codex and check again.', 'Codex 在 10 秒内没有响应。请打开 Codex 后重新检查。'] }; el('doctor-note').textContent = status?.ready ? (language === 'zh' ? `Codex 已连接 · ${status.projectCount} 个已有项目` : `Codex connected · ${status.projectCount} existing projects`) : (hints[status?.status]?.[language === 'zh' ? 1 : 0] || ''); } catch (error) { el('error').textContent = error.message; } }
let restored = false;
async function refresh() { try { const state = await api('status'); el('step').textContent = state.step; el('error').textContent = state.error || ''; el('messages').textContent = state.messages.join('\n'); ['login', 'deploy', 'start'].forEach(id => { el(id).disabled = state.busy; }); el('accounts').replaceChildren(...state.accounts.map(value => { const option = document.createElement('option'); option.value = value; return option; })); if (state.accounts.length === 1 && !el('account').value) el('account').value = state.accounts[0]; if (!restored && state.saved) { el('name').value = state.saved.name; el('account').value = state.saved.accountId; el('deploy').textContent = language === 'zh' ? '继续安装 / 检查连接' : 'Resume setup / verify connection'; restored = true; } } catch (error) { el('error').textContent = error.message; } }
el('check').onclick = doctor;
el('login').onclick = () => act('login');
el('tools').onclick = () => act('tools');
el('deploy').onclick = () => act('deploy', { accountId: el('account').value.trim(), name: el('name').value.trim(), costAccepted: el('cost').checked });
el('start').onclick = () => act('start');
el('updates').onclick = async () => { try { const result = await api('updates'); el('release').replaceChildren(document.createTextNode(`${result.current} → ${result.latest?.tag || '—'} `)); const link = document.createElement('a'); link.href = result.downloadUrl; link.target = '_blank'; link.rel = 'noreferrer'; link.textContent = language === 'zh' ? '发布说明与下载 ↗' : 'Release notes & downloads ↗'; el('release').append(link); } catch (error) { el('release').textContent = error.message; } };
translate(); doctor(); refresh(); setInterval(refresh, 2500);
